Repository DO-SOPT-CDS-SEMINAR/Apple-Server, pull requests merged in 2023-11, with the labels that each got.

#2 #1 [CHORE] 스프링 프로젝트 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/sopthapse/www/HapseProject/HapseProjectApplication.java
  src/main/java/org/sopthapse/www/HapseProject/controller/HealthCheckController.java
  src/test/java/org/sopthapse/www/HapseProject/HapseProjectApplicationTests.java
Labels: ✅ CHORE ✅ , 채은

#7 #4 [FEAT] 제품 목록 조회 API 구현
  src/main/java/org/sopthapse/www/HapseProject/controller/ProductController.java
  src/main/java/org/sopthapse/www/HapseProject/domain/Message.java
  src/main/java/org/sopthapse/www/HapseProject/domain/Product.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/Product/ProductGetResponse.java
  src/main/java/org/sopthapse/www/HapseProject/repository/ProductRepository.java
  src/main/java/org/sopthapse/www/HapseProject/service/ProductService.java
Labels: ✨ FEAT ✨, 채은

#8 #6 [FEAT] iPad Pro 배송 도착 정보 조회 API 구현
  src/main/java/org/sopthapse/www/HapseProject/controller/PaymentController.java
  src/main/java/org/sopthapse/www/HapseProject/service/PaymentService.java
Labels: ✨ FEAT ✨, 채은

#9 #5 [FEAT] 아이패드 뷰 내의 모든 제품 정보 조회 API 구현
  src/main/java/org/sopthapse/www/HapseProject/controller/IpadviewItemsController.java
  src/main/java/org/sopthapse/www/HapseProject/domain/IpadviewItems.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/IpadviewItems/IpadviewItemsGetResponse.java
  src/main/java/org/sopthapse/www/HapseProject/repository/IpadviewItemsRepository.java
  src/main/java/org/sopthapse/www/HapseProject/service/IpadviewItemsService.java
Labels: ✨ FEAT ✨, 채은

#10 #3 [FEAT] iPad Pro 악세서리 정보 조회 API 구현
  src/main/java/org/sopthapse/www/HapseProject/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/sopthapse/www/HapseProject/common/exception/BadRequestException.java
  src/main/java/org/sopthapse/www/HapseProject/common/exception/BaseException.java
  src/main/java/org/sopthapse/www/HapseProject/common/resopnse/ApiResponse.java
  src/main/java/org/sopthapse/www/HapseProject/controller/PaymentController.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/Accessory/AccessoryGetResponse.java
  src/main/java/org/sopthapse/www/HapseProject/service/PaymentService.java
Labels: ✨ FEAT ✨, 채은

#14 [FEAT] mainCategory 정보 조회 API구현 완료
  src/main/java/org/sopthapse/www/HapseProject/controller/MainController.java
  src/main/java/org/sopthapse/www/HapseProject/domain/MainCategory.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/Main/MainCategoryGetResponse.java
  src/main/java/org/sopthapse/www/HapseProject/repository/MainCategoryRepository.java
  src/main/java/org/sopthapse/www/HapseProject/service/MainCategoryService.java
Labels: ✨ FEAT ✨, 홍준

#18 #17 [FEAT] 제품 구입하기 이미지 조회 API 구현
  src/main/java/org/sopthapse/www/HapseProject/controller/ProductController.java
  src/main/java/org/sopthapse/www/HapseProject/domain/Product.java
  src/main/java/org/sopthapse/www/HapseProject/domain/ProductBuyImage.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/ProductBuyImage/ProductBuyImageGetResponse.java
  src/main/java/org/sopthapse/www/HapseProject/service/ProductService.java
Labels: ✨ FEAT ✨, 채은

#20 #19 [REFACTOR] Payment 관련 모든 API의 url, 클래스 변경
  src/main/java/org/sopthapse/www/HapseProject/controller/PaymentController.java
  src/main/java/org/sopthapse/www/HapseProject/controller/ProductController.java
  src/main/java/org/sopthapse/www/HapseProject/service/PaymentService.java
  src/main/java/org/sopthapse/www/HapseProject/service/ProductService.java
Labels: ♻️ REFACTOR ♻️ , 채은

#22 #21 [FEAT] CORS 정책 적용
  build.gradle
  src/main/java/org/sopthapse/www/HapseProject/config/SecurityConfig.java
Labels: ✨ FEAT ✨, 홍준, 채은

#26 [REFACTOR]상품 목록 조회 API반환값 수정
  .DS_Store
  src/main/java/org/sopthapse/www/HapseProject/domain/Product.java
  src/main/java/org/sopthapse/www/HapseProject/dto/response/Product/ProductGetResponse.java
Labels: ♻️ REFACTOR ♻️ , 홍준
